# Correlator Dataset Pattern Configuration
# =========================================
# This file maps tool-specific dataset URNs to canonical URNs for cross-tool correlation.
#
# Pattern syntax:
#   - {variable} captures any characters except "/"
#   - {variable*} captures any characters including "/" (for paths)
#   - Literal characters match exactly
#   - First matching pattern wins (order matters)
#
# Workflow:
#   1. Run your data tools (dbt, Airflow, GE) to ingest events
#   2. Check the Health page for orphan datasets
#   3. Add patterns below to map orphans to canonical URNs
#   4. Restart Correlator - correlation improves immediately

dataset_patterns:
  # Great Expectations → dbt dataset mapping
  # GE emits: demo_postgres/customers, demo_postgres/orders
  # dbt emits: postgresql://demo/marts.customers, postgresql://demo/marts.orders
  - pattern: "demo_postgres/{name}"
    canonical: "postgresql://demo/{name}"
