# golangci-lint configuration for Correlator
# Optimized for CI environments with resource constraints

run:
  timeout: 3m
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

linters:
  # Use only essential linters to reduce memory usage
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - unused
    - gofmt

  disable-all: true  # Disable all linters by default, only enable what we need

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Reduce checks to save resources

issues:
  max-issues-per-linter: 50  # Limit output to prevent excessive memory usage
  max-same-issues: 3
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck