# golangci-lint configuration for Correlator
# Tailored for a high-performance correlation engine backend

# Options for analysis running.
run:
  timeout: 5m
  go: '1.23'
  modules-download-mode: readonly
  allow-parallel-runners: true
  tests: true

# Output configuration options.
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# See the dedicated "linters" documentation section.
linters:
  # Enable specific linters
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - gocyclo
    - gosec
    - prealloc
    - goconst
    - misspell
    - lll
    - whitespace
    - errorlint
    - unconvert
    - dupl

  # Disable specific linters
  disable:
    - deadcode
    - structcheck
    - varcheck
    - scopelint
    - golint
    - interfacer
    - maligned
    - funlen
    - gocognit
    - godot

# All available settings of specific linters.
linters-settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    gocyclo:
      min-complexity: 12

    gosec:
      severity: medium
      confidence: medium

    govet:
      enable-all: true
      disable:
        - fieldalignment

    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: function-result-limit
          arguments: [3]
        - name: cyclomatic
          arguments: [12]

    lll:
      line-length: 120

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    dupl:
      threshold: 100

    errorlint:
      errorf: true
      asserts: true
      comparison: true

# See the dedicated "issues" documentation section.
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - goconst
        - gocyclo
        
    # Allow complex main functions for CLI tools
    - path: cmd/
      text: "cyclomatic complexity"
      linters:
        - gocyclo
        
    # Allow long lines in generated migration files
    - path: migrations/
      linters:
        - lll
        - goconst