# golangci-lint configuration for Correlator
# Based on official documentation: https://golangci-lint.run/docs/configuration/file/

version: "2"

run:
  timeout: 5m
  tests: true
  go: '1.25'
  concurrency: 4

linters:
  default: all

  disable:
    - depguard
    - exhaustruct
    - godox
    - varnamelen
    - wrapcheck
    - testpackage
    - paralleltest
    - tparallel
    - noinlineerr
    - wsl           # Deprecated, replaced by wsl_v5

  settings:
    cyclop:
      max-complexity: 15

    funlen:
      lines: 100
      statements: 50

    gocognit:
      min-complexity: 20

  # IMPORTANT: Exclusion rules to disable complexity linters for test files
  exclusions:
    rules:
      # Exclude complexity linters from running on test files
      - path: _test\.go
        linters:
          - cyclop        # Cyclomatic complexity - EXCLUDED for tests
          - funlen        # Function length - EXCLUDED for tests
          - gocognit      # Cognitive complexity - EXCLUDED for tests
          - gocyclo       # Cyclomatic complexity (different implementation)
          - maintidx      # Maintainability index
          - errcheck      # Unchecked errors (more lenient in tests)
          - dupl          # Code duplication (acceptable in tests)
          - gosec         # Security issues (more lenient in tests)
          - intrange
          - noinlineerr
          - goconst

issues:
  max-issues-per-linter: 20
  max-same-issues: 5
