# golangci-lint configuration for Correlator
# Minimal configuration compatible with v1.59.1

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell

  disable:
    - revive  # Temporarily disable until Phase 4 - causes issues with placeholder services
    - gosec   # Temporarily disable until Phase 4 - placeholder services trigger false positives

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec