# golangci-lint configuration for Correlator
# Minimal configuration compatible with v1.59.1

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - gosec
    - misspell

  disable: []

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gosec:
    severity: medium
    confidence: medium

  revive:
    rules:
      - name: exported
      - name: package-comments

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        
    - path: cmd/
      text: "cyclomatic complexity"