# Local development overrides
# This file is automatically merged with docker-compose.yml
services:
  postgres:
    environment:
      # Development-specific overrides
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev123}  # Default to dev123 if not set

    # Enable verbose logging for development
    command: [
      "postgres",
      "-c", "shared_buffers=256MB",
      "-c", "effective_cache_size=1GB",
      "-c", "work_mem=16MB",
      "-c", "random_page_cost=1.1",
      "-c", "effective_io_concurrency=200",
      "-c", "max_connections=100",
      "-c", "shared_preload_libraries=pg_stat_statements,pg_trgm",
      "-c", "wal_buffers=16MB",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "log_statement=all",
      "-c", "log_min_duration_statement=100",  # Log queries > 100ms in dev
      "-c", "log_destination=stderr",
      "-c", "logging_collector=off"
    ]

    volumes:
      # Mount migrations directory for easy development
      - ../../migrations:/migrations:ro

  correlator:
    environment:
      - DATABASE_URL=postgres://correlator:${POSTGRES_PASSWORD:-dev123}@postgres:5432/correlator?sslmode=disable
      - LOG_LEVEL=debug
      - DEVELOPMENT=true

    # Mount source code for development (when using air for hot reload)
    volumes:
      - ../..:/app:ro
