version: 2

models:
  - name: stg_customers
    description: "Staging model for raw customer data"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Full name of the customer"
        tests:
          - not_null

  - name: stg_orders
    description: "Staging model for raw order data"
    columns:
      - name: order_id
        description: "Unique identifier for the order"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: ordered_at
        description: "Timestamp when the order was placed"
        tests:
          - not_null
      - name: order_total
        description: "Total amount of the order"
        tests:
          - not_null
