version: 2

models:
  - name: customers
    description: "Customer mart with aggregated order statistics"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Full name of the customer"
        tests:
          - not_null
      - name: order_count
        description: "Total number of orders placed by the customer"
        tests:
          - not_null
      - name: total_amount
        description: "Total amount spent by the customer"
        tests:
          - not_null

  - name: orders
    description: "Orders mart enriched with customer information"
    columns:
      - name: order_id
        description: "Unique identifier for the order"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
      - name: order_total
        description: "Total amount of the order"
        tests:
          - not_null
